### ISSUE TITLE
Improve implementation of Core 2.0

### ISSUE THREAD

**Issue by eljenso** [Alsciende/netrunner-cards-json#254]
Moving the discussion from Alsciende/netrunnerdb#136 to this repository.

**Comment by Saintis** [comment]
(repeat of what I said in previous discussion)

Multiple versions of cards with the same name could be an elegant way of implementing Core 2.0 and any cards reprinted with the same name.

**Comment by gereons** [comment]
I would very much dislike relying on names as primary keys.

What the data model should allow for is that packs don't contain the cards themselves, but only lists of (code, quantity) referring to cards, but that's a huge change that would require major efforts/rewrites both in netrunnerdb.com itself and its existing API clients.

**Comment by Alsciende** [comment]
Let's keep the discussion in one place. Since it affects the data model, I'm closing this in favor of the original issue.
