### ISSUE TITLE
MWL 2.0 and Revised Core

### ISSUE THREAD

**Issue by NoahTheDuke** [Alsciende/netrunner-cards-json#264]
I've noticed a lot of ostensibly :rotato: and MWL 2.0 compliant decks be posted that contain cards from Core 1.0, Genesis, and Spin.

Until efforts to unite copies of cards (in something like #259) happen, might it be smart to put all of the rotated Core 1.0, Genesis, and Spin cards into the MWL 2.0 list? Or maybe create a second list that called "Rotation-MWL" that lists all rotated and MWL'd cards, so that the editor highlights any cards in Core 1.0 (or Genesis and Spin) and flags it as not-MWL compliant?

Another idea is to allow for creation of a deck, and then an option that says, "Convert to Rotation" and automatically changes all copies of cards from the rotated pool to their Revised Core version? I would whip something up, but I don't know exactly where to look to make that happen. I'd be willing to try if given a slight bit of direction, tho!

**Comment by jwarwick** [comment]
I'd prefer to keep the MWL separate from the rotation information. For jnet we use the `rotated` information from the cycles to mark individual cards as rotated, then search for cards with matching titles. If we find a match, we add a `replaces` or `replaced_by` field to those cards.

When we do deck construction/validation if a rotated card is used we replace it by following the `replaced_by` link if present.

**Comment by NoahTheDuke** [comment]
When a fix comes, it probably won't use this method, so no need to keep this open.
