### ISSUE TITLE
CircleCI is blocking PRs from other repos

### ISSUE THREAD

**Issue by gereons** [Alsciende/netrunner-cards-json#297]
@Alsciende can you take a look at the CircleCI config? PRs #295 and #296 are ready to be merged, but I can't, since they're waiting for the CI checks which apparently never run. 

This seems to be an issue with PRs from forked repos only, as the tests run almost instantly when there's a PR for a branch in this repo.

**Comment by Alsciende** [comment]
AFAIK CircleCI can't run tests on PR from other repos. I've started looking at TravisCI as a replacement.

**Comment by Alsciende** [comment]
I required master to be reviewed but not tested.

**Comment by gereons** [comment]
Works like a charm with Travis.
