### ISSUE TITLE
Decklists with Kitara cards marked as pre-rotation

### ISSUE THREAD

**Issue by hiddenaway1** [Alsciende/netrunner-cards-json#316]
Example: https://netrunnerdb.com/en/decklist/48211/say-dear-do-you-remember-the-time-when-

I believe it affects any decklist with a Kitara card added to it. I'm not 100% certain but I believe this can be fixed by adding kitara to the list in rotations.json:

> 
> [
>   {
>     "code": "rotation-2017",
>     "cycles": [
>       "creation-and-control",
>       "honor-and-profit",
>       "lunar",
>       "order-and-chaos",
>       "sansan",
>       "data-and-destiny",
>       "mumbad",
>       "flashpoint",
>       "red-sand",
>       "terminal-directive",
>       "core2"
>       **"kitara"**
>     ],
>     "name": "First Rotation",
>     "date_start": "2017-10-01"
>   }
> ]

I'll be happy to do the pull request but I want to make sure this is correct before I mess around with it.

**Comment by gereons** [comment]
Yes, that is the correct fix.

**Comment by Alsciende** [comment]
Fixed for future decklists. I'll see what I can do for past decklists.
