### ISSUE TITLE
Add System Core 2019 as a pack

### ISSUE THREAD

**Issue by psuessenb** [Alsciende/netrunner-cards-json#368]
System Core 2019 (the new Core Set from Project NISEI) should be added as a new cycle/pack:

http://nisei.net/article/SC2019
https://drive.google.com/file/d/1ECIihkYO9xvQfnsVUQicsY_SWpnys3ji/view

I think you are aware of this already, and I open this issue mainly because I thought about just providing a PR. I just don't know if you want to handle this like the Revisied Core Set (by duplicating most of the data) or if you want to introduce a new approach. I mean, the cards in this set are all existing cards, not even the artwork has changed. Only the quantity in which they are included in this new core changes.

**Comment by gereons** [comment]
As far as I can tell, the database schema for NetrunnerDB can only handle SC2019 if we add it like we did RCS: assign new card codes for each card, and update the quantity field for each. @NoahTheDuke what do you think?

**Comment by eljenso** [comment]
@gereons This is exactly what @NoahTheDuke did in his repo: https://github.com/NoahTheDuke/netrunner-data/blob/master/edn/set-cards/system-core-2019.edn

**Comment by gereons** [comment]
Then we should follow suit and make sure we use the same codes to avoid confusion.

**Comment by gereons** [comment]
Fixed via #369
