### ISSUE TITLE
Magnum Opus card images are scans rather than clear images

### ISSUE THREAD

**Issue by SpencerDub** [Alsciende/netrunner-cards-json#439]
The images for Magnum Opus cards, starting with [Labor Rights](https://netrunnerdb.com/en/card/23001), appear to be scans of printed cards. This seems unnecessary, given that we have the original images in the PDFs that FFG distributed.

Is there any reason we're using scans instead of the images from the PDFs? If not, can I round the corners of the images and use them to replace the scans?

**Comment by SpencerDub** [comment]
I believe @NoahTheDuke took care of this several months ago.

**Comment by NoahTheDuke** [comment]
Good catch! Thanks for checking in on this!
