### ISSUE TITLE
Does Gachapon have 1 influence or the card image's influence 2?

### ISSUE THREAD

**Issue by Mezuzi** [Alsciende/netrunner-cards-json#503]
Reporting for someone else's discovery on NRDB:

```
{
        "faction_code": "anarch",
        "faction_cost": 1,   # Is this number correct?
        "flavor": "Win a new friend today!",
        "illustrator": "Elizaveta Sokolova",
        ...
        "title": "Gachapon",
        "type_code": "hardware",
        "uniqueness": false
}
```

The [image on nisei.net](https://lh5.googleusercontent.com/eSnxOQI4nBLU-oTySamLqoGJqJTWqs2WhLi1jEEp6_RHY5BQkx4WGyxHPjSBVwa4PZxRFhkLB8femNOdVL5kODvIWVz0nWzr086GSzudGt0F2eeCgvo7kD79Wg8oOwaNppJW2NJ1) seems to suggest that this card is 2 influence.

**Comment by x3N1GM4x** [comment]
Good catch, thanks!

Will fix this now.
